fix: Kit integration forwarding unplanned/blocked events when fired early on app run
mParticle/mparticle-android-sdk pull request #394
Opened 2023-06-26 22:44 UTC by markvdouw

Kit integration forwarding unplanned/blocked events when fired early on app run

## Instructions
 1. PR target branch should be against `development`
 2. PR title name should follow this format: https://github.com/mParticle/mparticle-workflows/blob/main/.github/workflows/pr-title-check.yml
 3. PR branch prefix should follow this format: https://github.com/mParticle/mparticle-workflows/blob/main/.github/workflows/pr-branch-check-name.yml

 ## Summary
 - Dataplans was being updated before the config has been loaded, resulting on a race condition.

 ## Testing Plan
 - [x] Was this tested locally? If not, explain why.
 - {explain how this has been tested, and what, if any, additional testing should be done}
@mmustafa-tse was able to verify the fix.

 ## Reference Issue (For mParticle employees only.  Ignore if you are an outside contributor)
 - Closes https://mparticle-eng.atlassian.net/browse/SQDSDKS-5508

2023-06-27 13:30 UTC, samdozor requested changes

2023-06-27 13:30 UTC, samdozor commented on android-core/src/main/java/com/mparticle/internal/KitFrameworkWrapper.java
> +                                        updateDataplan(mCoreCallbacks.getDataplanOptions());
this reads like a race condition - we need to ensure that the data plan is set before kits are loaded. specifically - we need to make sure that no user attribute, events, etc can be sent to kits prior to the data plan.

in my view ideally we'd load the data plan in the same function `updateKits` above that loads kit configuration. the idea of KitConfiguration is that it should contain absolutely everything needed, and we only start kits after it's been completely parsed.

2023-06-28 11:58 UTC, samdozor approved these changes

2023-06-28 14:19 UTC, BrandonStalnaker approved these changes
LGTM

2023-06-28 17:26 UTC, merged

2023-06-28 18:28 UTC, mparticle-automation commented
:tada: This PR is included in version 5.51.3 :tada:

The release is available on [GitHub release](https://github.com/mParticle/mparticle-android-sdk/releases/tag/v5.51.3)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: