fix: SQDSDK-5597 - Get ad id in background thread
mParticle/mparticle-android-sdk pull request #463
Opened 2023-12-13 12:16 UTC by markvdouw

## Instructions
 1. PR target branch should be against `development`
 2. PR title name should follow this format: https://github.com/mParticle/mparticle-workflows/blob/main/.github/workflows/pr-title-check.yml
 3. PR branch prefix should follow this format: https://github.com/mParticle/mparticle-workflows/blob/main/.github/workflows/pr-branch-check-name.yml

 ## Summary
 - Move the getAdIdInfo to be triggered in a background thread

 ## Testing Plan
 - [x] Was this tested locally? If not, explain why.
 - Added a log printing the current thread in which the fun was being called (which was then removed prior to commit) 
<img width="1454" alt="Screen Shot 2023-12-13 at 09 11 52" src="https://github.com/mParticle/mparticle-android-sdk/assets/9582473/df9f74af-d3fc-4f32-ac01-aab8c34ec90c">

 ## Reference Issue (For mParticle employees only.  Ignore if you are an outside contributor)
 - Closes https://mparticle-eng.atlassian.net/browse/SQDSDKS-5867

2023-12-17 15:37 UTC, samdozor requested changes
would you mind also annotating the getAdIdInfo method with  @workerthread (or whatever the syntax is)?

2023-12-17 15:37 UTC, samdozor commented on android-core/src/main/java/com/mparticle/internal/MPUtility.java
> +import android.util.Log;
```suggestion
```

2024-01-08 16:27 UTC, markvdouw commented
> would you mind also annotating the getAdIdInfo method with @workerthread (or whatever the syntax is)?

This is already done

2024-01-09 17:10 UTC, markvdouw reviewed
Already has the @WorkerThread annotation in line 128

2024-01-29 15:49 UTC, samdozor approved these changes

2024-01-29 17:25 UTC, merged

2024-02-06 15:27 UTC, mparticle-automation commented
:tada: This PR is included in version 5.55.1 :tada:

The release is available on [GitHub release](https://github.com/mParticle/mparticle-android-sdk/releases/tag/v5.55.1)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: