refactor: Migrate Internal Constants class to kotlin
mParticle/mparticle-android-sdk pull request #510
Opened 2024-09-26 17:30 UTC by Mansi-mParticle

## Instructions
 1. PR target branch should be against `development`
 2. PR title name should follow this format: https://github.com/mParticle/mparticle-workflows/blob/main/.github/workflows/pr-title-check.yml
 3. PR branch prefix should follow this format: https://github.com/mParticle/mparticle-workflows/blob/main/.github/workflows/pr-branch-check-name.yml

 ## Summary
 - Migrate internal package’s Constants,BatchId,CoreCallbacks classes to Kotlin.

 ## Testing Plan
 - [x] Was this tested locally? If not, explain why.
 - Tested with sample application and ran the unit test cases

 ## Reference Issue (For mParticle employees only.  Ignore if you are an outside contributor)
 - Closes https://go.mparticle.com/work/SQDSDKS-6709

2024-10-01 18:02 UTC, rmi22186 requested changes

2024-10-01 18:51 UTC, Mansi-mParticle commented on android-core/src/main/java/com/mparticle/identity/IdentityApi.java
> +        if (Constants.TEMPORARY_MPID != mpid && mConfigManager.mpidExists(mpid)) {
because in Java long is primitive data type and in kotlin it's object so we nee to use != for object comparison

2024-10-01 18:51 UTC, Mansi-mParticle commented on android-core/src/main/java/com/mparticle/identity/IdentityApi.java
> +        if (Constants.TEMPORARY_MPID == updateRequest.mpid) {
because in Java long is primitive data type and in kotlin it's object so we nee to use != for object comparison

2024-10-01 18:52 UTC, Mansi-mParticle commented on android-core/src/main/kotlin/com/mparticle/internal/BatchId.kt
> +        get() = field
because val work like final and here on line 16 we need to initialize variable so it should be var

2024-10-01 18:57 UTC, Mansi-mParticle commented on android-core/src/main/kotlin/com/mparticle/internal/Constants.kt
> +            //sandbox mode is deprecated as of > 1.6.3
Ticket created : https://mparticle-eng.atlassian.net/browse/SQDSDKS-6814

2024-10-01 20:07 UTC, rmi22186 approved these changes

2024-10-02 15:39 UTC, einsteinx2 requested changes

2024-10-02 15:39 UTC, einsteinx2 commented on android-core/src/main/kotlin/com/mparticle/internal/BatchId.kt
> +        get() = field
We can use val here because we're assigning all values in both constructors.

2024-10-02 15:39 UTC, einsteinx2 commented on android-core/src/main/kotlin/com/mparticle/internal/BatchId.kt
> +        get() = field
These `get()` methods should be able to be removed as well since they just return the value which the automatic getter will already do.

2024-10-02 15:39 UTC, einsteinx2 commented on android-core/src/main/kotlin/com/mparticle/internal/BatchId.kt
> +        return arrayOf(mpid, sessionId, dataplanId, dataplanVersion)
We should move this into the `hashCode` method to simplify the class as this private function isn't used anywhere else

2024-10-02 15:41 UTC, einsteinx2 commented
Everything else looks good to go

2024-10-02 16:12 UTC, einsteinx2 commented on android-core/src/main/kotlin/com/mparticle/internal/BatchId.kt
> +        return arrayOf(mpid, sessionId, dataplanId, dataplanVersion)
Actually never mind, I see this is also used in the `equals` method

2024-10-02 21:45 UTC, einsteinx2 approved these changes

2024-10-03 03:16 UTC, merged

2024-10-15 19:41 UTC, mparticle-automation commented
:tada: This PR is included in version 5.58.3 :tada:

The release is available on [GitHub release](https://github.com/mParticle/mparticle-android-sdk/releases/tag/v5.58.3)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2024-10-24 20:13 UTC, mparticle-automation commented
:tada: This PR is included in version 5.58.3 :tada:

The release is available on [GitHub release](https://github.com/mParticle/mparticle-android-sdk/releases/tag/v5.58.3)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: