refactor: Migrate Internal ProviderPersistence class to kotlin
mParticle/mparticle-android-sdk pull request #533
Opened 2024-12-20 22:36 UTC by Mansi-mParticle

## Instructions
 1. PR target branch should be against `development`
 2. PR title name should follow this format: https://github.com/mParticle/mparticle-workflows/blob/main/.github/workflows/pr-title-check.yml
 3. PR branch prefix should follow this format: https://github.com/mParticle/mparticle-workflows/blob/main/.github/workflows/pr-branch-check-name.yml

 ## Summary
 - Migrate internal package’s ProviderPersistence classe to Kotlin.

 ## Testing Plan
 - [x] Was this tested locally? If not, explain why.
 - Tested with sample application and ran the unit test cases

 ## Reference Issue (For mParticle employees only.  Ignore if you are an outside contributor)
 - Closes https://go.mparticle.com/work/SQDSDKS-6978

2025-01-06 19:34 UTC, einsteinx2 requested changes
Just those questions about locale, otherwise looks good to me.

2025-01-06 19:34 UTC, einsteinx2 commented on android-core/src/main/kotlin/com/mparticle/internal/ProviderPersistence.kt
> +                defaultString = defaultString.lowercase(Locale.getDefault())
Are we sure we want to use the default locale here? I'm not saying we don't, but is this different in any way from the `toLowerCase()` function in Java? Does `getDefault()` get the current system default or some universal default? I've been bitten by locale bugs in the past, so I want to make sure we're 100% certain here.

2025-01-06 19:34 UTC, einsteinx2 commented on android-core/src/main/kotlin/com/mparticle/internal/ProviderPersistence.kt
> +            uuid = uuid.uppercase(Locale.getDefault())
Same concern about locale here.

2025-01-06 20:55 UTC, Mansi-mParticle commented on android-core/src/main/kotlin/com/mparticle/internal/ProviderPersistence.kt
> +                defaultString = defaultString.lowercase(Locale.getDefault())
so here Locale.getDefault() will return the default language for system. languages where case rules vary (e.g., Turkish).

2025-02-27 15:21 UTC, rmi22186 requested changes

2025-02-27 15:21 UTC, rmi22186 commented on android-core/src/main/kotlin/com/mparticle/internal/ProviderPersistence.kt
> +                val files = configPersistence.getJSONObject(i).getJSONArray(KEY_PERSISTENCE_ANDROID)
i suggest turn `configPersistence.getJSONObject(i)` into a variable for readability

2025-02-27 15:21 UTC, rmi22186 commented on android-core/src/main/kotlin/com/mparticle/internal/ProviderPersistence.kt
> +                        val mpKey = fileObjects.getJSONObject(keyIndex).getString(KEY_PERSISTENCE_MPVAR)
i suggest turn `fileObjects.getJSONObject(keyIndex)` into a variable for readability

2025-02-27 15:21 UTC, rmi22186 commented on android-core/src/main/kotlin/com/mparticle/internal/ProviderPersistence.kt
> +        }
there's a lot of else if statement's here, it looks like it can be updated to be more readable as follows, similar to what you did on line 42-46:

```
private fun applyMacro(defaultString: String): String {
    val lowerDefault = defaultString.lowercase(Locale.getDefault())
    return when {
        isEmpty(defaultString) || !lowerDefault.startsWith("%") -> defaultString
        lowerDefault == MACRO_GUID_NO_DASHES -> UUID.randomUUID().toString().replace("-", "")
        lowerDefault == MACRO_OMNITURE_AID -> generateAID()
        lowerDefault == MACRO_GUID -> UUID.randomUUID().toString()
        lowerDefault == MACRO_TIMESTAMP -> System.currentTimeMillis().toString()
        lowerDefault == MACRO_GUID_LEAST_SIG -> UUID.randomUUID().leastSignificantBits.toString()
        else -> defaultString
    }
}
```
(please check this work above if you agree)

2025-03-04 14:59 UTC, rmi22186 approved these changes
LGTM.  can you make sure the tests are passing though?  might just need a rebase

2025-03-05 15:07 UTC, merged